	data-id-scroll
	data-autoinit="true"
	data-duration="1"
	data-orientation="vertical"
	data-smoothWheel="true"
	data-smoothTouch="false"
	data-touchMultiplier="1.5"
	data-easing="(t) => (t === 1 ? 1 : 1 - Math.pow(2, -10 * t))"
	data-useOverscroll="true"
	data-useControls="true"
	data-useAnchor="true"
	data-useRaf="true"
	data-infinite="false"
	defer
	src="https://cdn.jsdelivr.net/gh/Joao-Aquino/webflow-scripts@main/geral/smooth-scrool.js"